### ISSUE TITLE
TextEditor has been disposed error

### ISSUE THREAD

**Issue by cdeil** [stkb/Rewrap#100]
I got this error and rewrap didn't work on the current editor.

Not sure if that is useful to you, but the message said to report it, so here you go ...

```
console.ts:136 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:136
console.ts:136 [Extension Host] ====== Rewrap: Error ======
t.log @ console.ts:136
console.ts:136 [Extension Host] DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed
    at Object.t.disposed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:170:338)
    at e.$tryApplyEdits (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3284:142)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3204:519)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3204:237)
    at e._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3203:312)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3203:81)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3202:10
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3205:93
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:532)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:312)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:531)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
console.ts:136 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
t.log @ console.ts:136
console.ts:136 [Extension Host] ====== Rewrap: Error ======
t.log @ console.ts:136
console.ts:136 [Extension Host] DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed
    at Object.t.disposed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:170:338)
    at e.$tryApplyEdits (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3284:142)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3204:519)
    at e._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3204:237)
    at e._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3203:312)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3203:81)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3202:10
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3205:93
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:172:532)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:312)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:307:531)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
console.ts:136 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
```

**Comment by stkb** [comment]
An attempt at fixing this is in the latest pre-release version. Trying to get the number of open issues down to a manageable level so since this is a rare bug I'm closing.
