### ISSUE TITLE
Cannot rewrap text in a ChangeLog file

### ISSUE THREAD

**Issue by svillar** [stkb/Rewrap#184]
This is the error:
```
[Extension Host] RangeError: Maximum call stack size exceeded
at isNullOrWhiteSpace (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/fable-core/String.js:297:45)
at isBlank (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/Core/Line.js:30:42)
at loop (~/.vscode/extensions/stkb.rewrap-.9.1/vscode/compiled/Core/Nonempty.js:239:11)
at ~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/fable-core/CurriedLambda.js:26:16
at curriedFn (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/fable-core/CurriedLambda.js:17:19)
at ~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/Core/Nonempty.js:251:71
at curriedFn (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/fable-core/CurriedLambda.js:17:19)
at ~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/Core/Parsing.Core.js:61:8
at curriedFn (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/fable-core/CurriedLambda.js:17:19)
at loop (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/Core/Parsing.Core.js:86:24)
at loop (~/.vscode/extensions/stkb.rewrap-1.9.1/vscode/compiled/Core/Parsing.Core.js:94:16)
...
(tons of repetitions of the last line)
```

**Comment by stkb** [comment]
Putting in #194
