### ISSUE TITLE
[Extension Host] Error: Offset greater than text length.

### ISSUE THREAD

**Issue by xmascoffee** [stkb/Rewrap#234]
```
	at positionAt (c:\Users\xmascoffee\.vscode\extensions\stkb.rewrap-1.13.0\vscode\FixSelections.js:84:11)
	at c:\Users\xmascoffee\.vscode\extensions\stkb.rewrap-1.13.0\vscode\FixSelections.js:37:21
	at Array.map (<anonymous>)
	at c:\Users\xmascoffee\.vscode\extensions\stkb.rewrap-1.13.0\vscode\FixSelections.js:33:14
	at Array.map (<anonymous>)
	at module.exports (c:\Users\xmascoffee\.vscode\extensions\stkb.rewrap-1.13.0\vscode\FixSelections.js:31:29)
	at c:\Users\xmascoffee\.vscode\extensions\stkb.rewrap-1.13.0\vscode\Extension.js:141:38
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by heyheyhello** [comment]
```
console.ts:137 [Extension Host] ====== Rewrap: Error ======
console.ts:137 [Extension Host] Error: Offset greater than text length.
at positionAt (/home/today/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:71:11)
at /home/today/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:28:21
at Array.map (<anonymous>)
at /home/today/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:24:14
at Array.map (<anonymous>)
at Object.default_1 [as default] (/home/today/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:22:29)
at /home/today/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/Common.js:44:56
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
```

Unfortunately I'm not able to reproduce the issue even after repeating the exact same actions and typed words...

I was writing in an `.md` file at an indented bullet list and rewrap had autowrapped because the last word was too long. So with the cursor on the newly wrapped line, I replaced the long word with "I" knowing it would fit on the previous line. I pressed Alt+Q and the "I" moved back up to the previous line as expected. Everything worked fine but Rewrap displayed the error notification.
