### ISSUE TITLE
Cannot switch off word wrap. Getting error

### ISSUE THREAD

**Issue by Skeeve** [stkb/Rewrap#270]
Developer Tools / Console asked me to paste this here.

```
console.ts:137 [Extension Host] ====== Rewrap: Error ======
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] Error: Offset greater than text length.	at positionAt (/Users/skeeve/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:71:11)	at /Users/skeeve/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:28:21	at Array.map (<anonymous>)	at /Users/skeeve/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:24:14	at Array.map (<anonymous>)	at Object.default_1 [as default] (/Users/skeeve/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/FixSelections.js:22:29)	at /Users/skeeve/.vscode-oss/extensions/stkb.rewrap-1.14.0/vscode/compiled/Common.js:44:56	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:97:5)
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
```

**Comment by stkb** [comment]
Thanks for posting. The error came from the the fixing of selections after wrapping, but I don't know more. The code for this has just been rewritten also. As there's not really much more to do here I'm closing this
