### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by jonas-frey** [stkb/Rewrap#283]
I got a popup saying that there was an error in rewrap and that I should open the developer console. There I saw the following.
I'm reporting it here as recommended at the end of the pasted text.

```
console.ts:137 [Extension Host] (node:59445) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
viewer.js:1581 PDF cd300d3a1945d6b2791d0a5bfbaedf05 [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.8.335)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'text' of undefined
	at vscode-file://vscode-app/home/jonas/.vscode/extensions/draivin.hsnips-0.2.1/out/extension.js:114
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at D.$acceptDirtyStateChanged (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85)
	at h._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at r._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at v.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at Socket.w (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
console.ts:137 [Extension Host] Error: Illegal argument: character must be non-negative	at D (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:78:18016)	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:78:17347)	at Object.rangeDeltaNewRange (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/text-util.js:49:42)	at DocumentController.applyChanges (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:74:44)	at DocumentController.onChangeDocument (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:83:14)	at /home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:18:22	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at D.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:148483)	at h._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12819)	at h._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12503)	at h._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11159)	at h._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9943)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8039	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:30060	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)	at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21091)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17969	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13186)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12534	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:13218)	at Socket.emit (events.js:315:20)	at addChunk (internal/streams/readable.js:309:12)	at readableAddChunk (internal/streams/readable.js:284:9)	at Socket.Readable.push (internal/streams/readable.js:223:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
S @ console.ts:137
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'text' of undefined
	at vscode-file://vscode-app/home/jonas/.vscode/extensions/draivin.hsnips-0.2.1/out/extension.js:114
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at D.$acceptDirtyStateChanged (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85)
	at h._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at r._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at v.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at Socket.w (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'text' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'text' of undefined
	at vscode-file://vscode-app/home/jonas/.vscode/extensions/draivin.hsnips-0.2.1/out/extension.js:114
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at D.$acceptDirtyStateChanged (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85)
	at h._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at h._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at c.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at r._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at d.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57)
	at v.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65)
	at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65
	at Socket.w (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
console.ts:137 [Extension Host] Error: Illegal argument: character must be non-negative	at D (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1232)	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:78:18016)	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:78:17347)	at Object.rangeDeltaNewRange (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/text-util.js:49:42)	at DocumentController.applyChanges (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:74:44)	at DocumentController.onChangeDocument (/home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:83:14)	at /home/jonas/.vscode/extensions/draivin.hscopes-0.0.6/out/src/document.js:18:22	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at D.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:148483)	at h._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12819)	at h._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12503)	at h._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11159)	at h._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9943)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8039	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:30060	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)	at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21091)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17969	at d.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13186)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12534	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:13218)	at Socket.emit (events.js:315:20)	at addChunk (internal/streams/readable.js:309:12)	at readableAddChunk (internal/streams/readable.js:284:9)	at Socket.Readable.push (internal/streams/readable.js:223:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
S @ console.ts:137
console.ts:137 [Extension Host] ====== Rewrap: Error ======
S @ console.ts:137
console.ts:137 [Extension Host] DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed    at h (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)    at ua.$tryApplyEdits (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:20393)    at r._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11989)    at r._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11673)    at r._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:10335)    at r._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:9122)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:7218    at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)    at n.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)    at u._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621    at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)    at b.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186    at Socket.T (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2899:159022)    at Socket.emit (events.js:315:20)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
S @ console.ts:137
```

**Comment by stkb** [comment]
```
console.ts:137 [Extension Host] ====== Rewrap: Error ======
S @ console.ts:137
console.ts:137 [Extension Host] DISPOSED: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed    at h (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:8:1581)    at ua.$tryApplyEdits (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2412:20393)    at r._doInvokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11989)    at r._invokeHandler (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:11673)    at r._receiveRequest (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:10335)    at r._receiveOneMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:9122)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1551:7218    at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)    at n.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16477)    at u._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21743)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:18621    at l.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)    at b.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13838)    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13186    at Socket.T (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2899:159022)    at Socket.emit (events.js:315:20)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues
S @ console.ts:137
```

Thanks for the stack trace, though this is the only part of it that pertains to Rewrap (before that is from the draivin.hsnips-0.2.1 extension). Since the error seems to be something weird that happend with VSCode ("TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed") there's not much I can do with this. So I'm going to close.
