### ISSUE TITLE
MoveNext not a function error

### ISSUE THREAD

**Issue by plafer** [stkb/Rewrap#311]
I got the following error, which VS code's console indicated I should report this here. The message is as follows:

> workbench.desktop.main.js:77 [Extension Host] ====== Rewrap: Error ======
I @ workbench.desktop.main.js:77
workbench.desktop.main.js:77 [Extension Host] TypeError: e.System.Collections.IEnumerator.MoveNext is not a function    at $c4c313718bcc393b$export$2344b14b097df817 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:6963:69)    at $044d4a9a60b1f629$export$47bd1dafac8b8c58 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:9057:12)    at /home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12577:148    at $c4c313718bcc393b$export$d65cb303b863e3bf (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:7071:17)    at $840f1b1ae3c3949d$export$78262f0a7b75cf50 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12577:92)    at $840f1b1ae3c3949d$export$2e6c959c16ff56b8 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12584:49)    at $900a7436dc584467$export$6cb9d9886761bf2b (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13030:23)    at $900a7436dc584467$export$4fb73e9c1c14efbc (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13085:30)    at $3a2783b7990735e4$var$checkChange (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13434:22)    at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)    at P.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:72180)    at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13802)    at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13486)    at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12148)    at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10826)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8922    at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)    at r.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34341    at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)    at r.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)    at n._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:23523)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21057    at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)    at w.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15770)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14900    at Socket.T (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:13813)    at Socket.emit (events.js:315:20)    at Socket.EventEmitter.emit (domain.js:467:12)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
workbench.desktop.main.js:577   ERR [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
workbench.desktop.main.js:77 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues

**Comment by stkb** [comment]
Hi, I need to improve the logging when errors occur, but do you have any more information such as what was the file type you were using and do you have any extensions installed for it?

**Comment by stkb** [comment]
I think this was caused by another language extension, but until there's more information here, I'm going to close this. Thanks for reporting anyway; it reminded me I need to put information like file type in the log when errors occur.

**Comment by plafer** [comment]
Sorry, I was only able to reproduce once on a Python file (with the standard Python extension), and forgot to update this thread. Will post back here if it keeps happening and the error messages are updated.

**Comment by plafer** [comment]
Got it again, on a simple txt file

workbench.desktop.main.js:75 [Extension Host] ====== Rewrap: Error ======
I @ workbench.desktop.main.js:75
workbench.desktop.main.js:75 [Extension Host] TypeError: e.System.Collections.IEnumerator.MoveNext is not a function    at $c4c313718bcc393b$export$2344b14b097df817 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:6963:69)    at $044d4a9a60b1f629$export$47bd1dafac8b8c58 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:9057:12)    at /home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12577:148    at $c4c313718bcc393b$export$d65cb303b863e3bf (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:7071:17)    at $840f1b1ae3c3949d$export$78262f0a7b75cf50 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12577:92)    at $840f1b1ae3c3949d$export$2e6c959c16ff56b8 (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:12584:49)    at $900a7436dc584467$export$6cb9d9886761bf2b (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13030:23)    at $900a7436dc584467$export$4fb73e9c1c14efbc (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13085:30)    at $3a2783b7990735e4$var$checkChange (/home/plafer/.vscode/extensions/stkb.rewrap-1.16.1/dist/Extension.js:13434:22)    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)    at y.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:71603)    at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13801)    at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13485)    at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:12147)    at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:10825)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:8934    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)    at s.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34390    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)    at s.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)    at a._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:23583)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:21117    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)    at _.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:15833)    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:14963    at Socket.A (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:13838)    at Socket.emit (events.js:315:20)    at Socket.EventEmitter.emit (domain.js:467:12)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
workbench.desktop.main.js:578   ERR [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues

**Comment by stkb** [comment]
Thanks. I know where it's happening but still can't work out why. It's just happening sporadically (ie you can't reproduce it)?

**Comment by plafer** [comment]
Oh I just figured it out: I only get the error when I have multiple VS code windows open.

**Comment by stkb** [comment]
Ok thanks. If you can find the steps to reproduce it will be a great help.

**Comment by plafer** [comment]
Still trying to figure those out... It just happened again, but this time with just one VS code window opened.

**Comment by stkb** [comment]
Does it happen when manual wrapping, or from autowrap when typing?

**Comment by plafer** [comment]
It happens from autowrap when typing.

**Comment by levity** [comment]
This happens to me in a Typescript file, when manual wrapping.

**Comment by levity** [comment]
It stopped happening after I updated and restarted VS Code 🎉

**Comment by stkb** [comment]
For anyone experiencing this, you can try switching to the pre-release version. I can't guarantee that it will stop it happening but there is some rewritten code there so it may do.

**Comment by matthiasgeihs** [comment]
Just happened yet again for me. 🙁

---
Update: working again after updating VSCode.

---
Update 2:

And then it stopped working right after that when the next VSCode update was incoming.

My conclusion: Whenever a VSCode update is pending, Rewrap stops working, due to the error posted in https://github.com/stkb/Rewrap/issues/311#issuecomment-1034168098 (`TypeError: e.System.Collections.IEnumerator.MoveNext is not a function`).

**Comment by matthiasgeihs** [comment]
And then it stopped working right after that when the next VSCode update was incoming.

My conclusion: Whenever a VSCode update is pending, Rewrap stops working, due to the error posted in https://github.com/stkb/Rewrap/issues/311#issuecomment-1034168098 (`TypeError: e.System.Collections.IEnumerator.MoveNext is not a function`).
