### ISSUE TITLE
Rewrap reports error and does not work

### ISSUE THREAD

**Issue by TheNetAdmin** [stkb/Rewrap#323]
I'm trying to rewrap a text file on vscode, but get rewrap errors (observed in vscode->Help->Developer Tools->Console as follows) and no text is rewrapped

Is this a known issue that has a solution? Or is there any temporary workaround?

```log
  ERR [Extension Host] ====== Rewrap: Error ======
console.ts:137 [Extension Host] ====== Rewrap: Error ======
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

console.ts:137 [Extension Host] Error: Edit is only valid while callback runs	at D._throwIfFinalized (c:\Users\89832\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:44211)	at D.delete (c:\Users\89832\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:44550)	at c:\Users\89832\.vscode\extensions\stkb.rewrap-17.7.0\dist\Extension.js:15125:91	at Array.forEach (<anonymous>)	at $9e2fa7da53fb418a$export$db4041490cae3922 (c:\Users\89832\.vscode\extensions\stkb.rewrap-17.7.0\dist\Extension.js:15125:19)	at $09ff662961d6d81c$var$doWrap (c:\Users\89832\.vscode\extensions\stkb.rewrap-17.7.0\dist\Extension.js:15443:9)	at $09ff662961d6d81c$var$rewrapCommentAtCommand (c:\Users\89832\.vscode\extensions\stkb.rewrap-17.7.0\dist\Extension.js:15418:5)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
log.ts:313   ERR [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues

I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

And the screenshot of this error message:
![image](https://user-images.githubusercontent.com/18525442/154866951-9fc22fbd-01ea-48c4-99d9-51c14c2bd4e5.png)

The system information:
- OS: Windows 10
- rewrap: pre-release v17.7.0
- vscode: 
    ```
    Version: 1.64.2 (user setup)
    Commit: f80445acd5a3dadef24aa209168452a3d97cc326
    Date: 2022-02-09T22:02:28.252Z
    Electron: 13.5.2
    Chromium: 91.0.4472.164
    Node.js: 14.16.0
    V8: 9.1.269.39-electron.0
    OS: Windows_NT x64 10.0.19044
    ```

**Comment by stkb** [comment]
Thanks, closing as dup of #324

**Comment by stkb** [comment]
BTW if you need to you can temporarily go back to the stable version or I believe  pre-release version 17.4 as they don't have the change that broke this.
